// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySync(arg1, arg2) {
  return window['go']['main']['App']['ApplySync'](arg1, arg2);
}

export function CheckDocker() {
  return window['go']['main']['App']['CheckDocker']();
}

export function CloneServiceTemplate(arg1) {
  return window['go']['main']['App']['CloneServiceTemplate'](arg1);
}

export function CloneVolumeData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneVolumeData'](arg1, arg2, arg3, arg4);
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function CreateNode(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateNode'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateNodeFromTemplate(arg1) {
  return window['go']['main']['App']['CreateNodeFromTemplate'](arg1);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function CreateSandbox(arg1) {
  return window['go']['main']['App']['CreateSandbox'](arg1);
}

export function CreateServiceTemplate(arg1) {
  return window['go']['main']['App']['CreateServiceTemplate'](arg1);
}

export function DaemonConnection() {
  return window['go']['main']['App']['DaemonConnection']();
}

export function DeleteAppSecret(arg1) {
  return window['go']['main']['App']['DeleteAppSecret'](arg1);
}

export function DeleteEnvVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1, arg2);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteManagedVolume(arg1, arg2) {
  return window['go']['main']['App']['DeleteManagedVolume'](arg1, arg2);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectEnvVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteProjectEnvVar'](arg1, arg2);
}

export function DeleteSandbox(arg1) {
  return window['go']['main']['App']['DeleteSandbox'](arg1);
}

export function DeleteSandboxProfile(arg1) {
  return window['go']['main']['App']['DeleteSandboxProfile'](arg1);
}

export function DeleteServiceTemplate(arg1) {
  return window['go']['main']['App']['DeleteServiceTemplate'](arg1);
}

export function DeployService(arg1) {
  return window['go']['main']['App']['DeployService'](arg1);
}

export function DiscardStagedChanges(arg1) {
  return window['go']['main']['App']['DiscardStagedChanges'](arg1);
}

export function DuplicateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DuplicateEnvironment'](arg1, arg2, arg3);
}

export function ExportConfig(arg1, arg2) {
  return window['go']['main']['App']['ExportConfig'](arg1, arg2);
}

export function ExportConfigToPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportConfigToPath'](arg1, arg2, arg3);
}

export function ExportEnvFile(arg1) {
  return window['go']['main']['App']['ExportEnvFile'](arg1);
}

export function ExportProjectConfig(arg1, arg2) {
  return window['go']['main']['App']['ExportProjectConfig'](arg1, arg2);
}

export function ExtendSandbox(arg1, arg2) {
  return window['go']['main']['App']['ExtendSandbox'](arg1, arg2);
}

export function GetActiveDeployment(arg1) {
  return window['go']['main']['App']['GetActiveDeployment'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetBuildLog(arg1) {
  return window['go']['main']['App']['GetBuildLog'](arg1);
}

export function GetDefaultEnvironment(arg1) {
  return window['go']['main']['App']['GetDefaultEnvironment'](arg1);
}

export function GetDeployments(arg1) {
  return window['go']['main']['App']['GetDeployments'](arg1);
}

export function GetDockerDiskUsage() {
  return window['go']['main']['App']['GetDockerDiskUsage']();
}

export function GetEnvVars(arg1) {
  return window['go']['main']['App']['GetEnvVars'](arg1);
}

export function GetEnvironmentConnections(arg1) {
  return window['go']['main']['App']['GetEnvironmentConnections'](arg1);
}

export function GetGitHookStatus(arg1, arg2) {
  return window['go']['main']['App']['GetGitHookStatus'](arg1, arg2);
}

export function GetLinkedServiceInfo(arg1) {
  return window['go']['main']['App']['GetLinkedServiceInfo'](arg1);
}

export function GetLocalDomainStatus() {
  return window['go']['main']['App']['GetLocalDomainStatus']();
}

export function GetNode(arg1) {
  return window['go']['main']['App']['GetNode'](arg1);
}

export function GetNodeConfigStatus(arg1) {
  return window['go']['main']['App']['GetNodeConfigStatus'](arg1);
}

export function GetNodeHealth(arg1) {
  return window['go']['main']['App']['GetNodeHealth'](arg1);
}

export function GetNodeSettings(arg1) {
  return window['go']['main']['App']['GetNodeSettings'](arg1);
}

export function GetSandboxDetail(arg1) {
  return window['go']['main']['App']['GetSandboxDetail'](arg1);
}

export function GetSandboxProjectSettings(arg1) {
  return window['go']['main']['App']['GetSandboxProjectSettings'](arg1);
}

export function GetServiceMetrics(arg1) {
  return window['go']['main']['App']['GetServiceMetrics'](arg1);
}

export function GetServiceRoot(arg1, arg2) {
  return window['go']['main']['App']['GetServiceRoot'](arg1, arg2);
}

export function GetServiceTemplate(arg1) {
  return window['go']['main']['App']['GetServiceTemplate'](arg1);
}

export function ImportConfigAsProject(arg1, arg2) {
  return window['go']['main']['App']['ImportConfigAsProject'](arg1, arg2);
}

export function ImportConfigIntoProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportConfigIntoProject'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportConfigPreview(arg1) {
  return window['go']['main']['App']['ImportConfigPreview'](arg1);
}

export function ImportEnvFile(arg1, arg2) {
  return window['go']['main']['App']['ImportEnvFile'](arg1, arg2);
}

export function InspectDockerfileBuildInfo(arg1) {
  return window['go']['main']['App']['InspectDockerfileBuildInfo'](arg1);
}

export function IsGitRepo(arg1, arg2) {
  return window['go']['main']['App']['IsGitRepo'](arg1, arg2);
}

export function ListAllDockerVolumes() {
  return window['go']['main']['App']['ListAllDockerVolumes']();
}

export function ListAppSecretUsages(arg1) {
  return window['go']['main']['App']['ListAppSecretUsages'](arg1);
}

export function ListAppSecrets() {
  return window['go']['main']['App']['ListAppSecrets']();
}

export function ListDockerContainers() {
  return window['go']['main']['App']['ListDockerContainers']();
}

export function ListDockerImages() {
  return window['go']['main']['App']['ListDockerImages']();
}

export function ListDockerNetworks() {
  return window['go']['main']['App']['ListDockerNetworks']();
}

export function ListEnvironments(arg1) {
  return window['go']['main']['App']['ListEnvironments'](arg1);
}

export function ListGitBranches(arg1, arg2) {
  return window['go']['main']['App']['ListGitBranches'](arg1, arg2);
}

export function ListManagedVolumes(arg1, arg2) {
  return window['go']['main']['App']['ListManagedVolumes'](arg1, arg2);
}

export function ListNodes(arg1) {
  return window['go']['main']['App']['ListNodes'](arg1);
}

export function ListNodesWithReferenceIssues(arg1) {
  return window['go']['main']['App']['ListNodesWithReferenceIssues'](arg1);
}

export function ListProjectEnvVarUsages(arg1, arg2) {
  return window['go']['main']['App']['ListProjectEnvVarUsages'](arg1, arg2);
}

export function ListProjectEnvVars(arg1) {
  return window['go']['main']['App']['ListProjectEnvVars'](arg1);
}

export function ListProjectServices(arg1) {
  return window['go']['main']['App']['ListProjectServices'](arg1);
}

export function ListProjectServicesSummary(arg1) {
  return window['go']['main']['App']['ListProjectServicesSummary'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListReferenceIssues(arg1) {
  return window['go']['main']['App']['ListReferenceIssues'](arg1);
}

export function ListReferenceTargets(arg1) {
  return window['go']['main']['App']['ListReferenceTargets'](arg1);
}

export function ListRoutes(arg1) {
  return window['go']['main']['App']['ListRoutes'](arg1);
}

export function ListSandboxProfiles(arg1) {
  return window['go']['main']['App']['ListSandboxProfiles'](arg1);
}

export function ListSandboxes(arg1) {
  return window['go']['main']['App']['ListSandboxes'](arg1);
}

export function ListServiceTemplates() {
  return window['go']['main']['App']['ListServiceTemplates']();
}

export function ListShareableRoots(arg1, arg2) {
  return window['go']['main']['App']['ListShareableRoots'](arg1, arg2);
}

export function ListVolumesOverview() {
  return window['go']['main']['App']['ListVolumesOverview']();
}

export function ParseDockerfileExpose(arg1, arg2) {
  return window['go']['main']['App']['ParseDockerfileExpose'](arg1, arg2);
}

export function PreviewCloneVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewCloneVolume'](arg1, arg2, arg3);
}

export function PreviewDeleteService(arg1) {
  return window['go']['main']['App']['PreviewDeleteService'](arg1);
}

export function PreviewEnvVars(arg1) {
  return window['go']['main']['App']['PreviewEnvVars'](arg1);
}

export function PreviewEnvironmentDuplicate(arg1) {
  return window['go']['main']['App']['PreviewEnvironmentDuplicate'](arg1);
}

export function PreviewSandbox(arg1) {
  return window['go']['main']['App']['PreviewSandbox'](arg1);
}

export function PreviewStagedChanges(arg1, arg2) {
  return window['go']['main']['App']['PreviewStagedChanges'](arg1, arg2);
}

export function PreviewSync(arg1) {
  return window['go']['main']['App']['PreviewSync'](arg1);
}

export function PromoteLinkedService(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteLinkedService'](arg1, arg2, arg3);
}

export function PruneDocker(arg1, arg2) {
  return window['go']['main']['App']['PruneDocker'](arg1, arg2);
}

export function ReapplyTemplate(arg1) {
  return window['go']['main']['App']['ReapplyTemplate'](arg1);
}

export function RedeployEnvironment(arg1) {
  return window['go']['main']['App']['RedeployEnvironment'](arg1);
}

export function RefreshEnvFile(arg1) {
  return window['go']['main']['App']['RefreshEnvFile'](arg1);
}

export function RemoveDockerContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveDockerContainer'](arg1, arg2);
}

export function RemoveDockerImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveDockerImage'](arg1, arg2);
}

export function RemoveDockerNetwork(arg1) {
  return window['go']['main']['App']['RemoveDockerNetwork'](arg1);
}

export function RemoveDockerVolume(arg1, arg2) {
  return window['go']['main']['App']['RemoveDockerVolume'](arg1, arg2);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function RestartDockerContainer(arg1) {
  return window['go']['main']['App']['RestartDockerContainer'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function ResumeSandbox(arg1) {
  return window['go']['main']['App']['ResumeSandbox'](arg1);
}

export function RollbackDeployment(arg1) {
  return window['go']['main']['App']['RollbackDeployment'](arg1);
}

export function RollbackEligibility(arg1) {
  return window['go']['main']['App']['RollbackEligibility'](arg1);
}

export function RunCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2, arg3);
}

export function SaveSandboxProfile(arg1) {
  return window['go']['main']['App']['SaveSandboxProfile'](arg1);
}

export function SaveSandboxProjectSettings(arg1) {
  return window['go']['main']['App']['SaveSandboxProjectSettings'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectServiceRoot(arg1) {
  return window['go']['main']['App']['SelectServiceRoot'](arg1);
}

export function SetAppSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAppSecret'](arg1, arg2, arg3);
}

export function SetAppSettings(arg1) {
  return window['go']['main']['App']['SetAppSettings'](arg1);
}

export function SetDefaultEnvironment(arg1) {
  return window['go']['main']['App']['SetDefaultEnvironment'](arg1);
}

export function SetDeployTrigger(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDeployTrigger'](arg1, arg2, arg3);
}

export function SetEnvVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2, arg3);
}

export function SetEnvVarScope(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVarScope'](arg1, arg2, arg3);
}

export function SetNodeSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNodeSetting'](arg1, arg2, arg3);
}

export function SetProjectEnvVar(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetProjectEnvVar'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRedeployOnPull(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRedeployOnPull'](arg1, arg2, arg3);
}

export function SetServiceRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServiceRoot'](arg1, arg2, arg3);
}

export function StageEnvVarChanges(arg1, arg2, arg3) {
  return window['go']['main']['App']['StageEnvVarChanges'](arg1, arg2, arg3);
}

export function StageNodeSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['StageNodeSettings'](arg1, arg2, arg3);
}

export function StartDocker() {
  return window['go']['main']['App']['StartDocker']();
}

export function StartDockerContainer(arg1) {
  return window['go']['main']['App']['StartDockerContainer'](arg1);
}

export function StartEnvironment(arg1) {
  return window['go']['main']['App']['StartEnvironment'](arg1);
}

export function StartLogStream(arg1) {
  return window['go']['main']['App']['StartLogStream'](arg1);
}

export function StopDockerContainer(arg1) {
  return window['go']['main']['App']['StopDockerContainer'](arg1);
}

export function StopEnvironment(arg1) {
  return window['go']['main']['App']['StopEnvironment'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function SuggestEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SuggestEnvFile'](arg1, arg2);
}

export function SuspendSandbox(arg1) {
  return window['go']['main']['App']['SuspendSandbox'](arg1);
}

export function UnlinkService(arg1, arg2) {
  return window['go']['main']['App']['UnlinkService'](arg1, arg2);
}

export function UpdateNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2, arg3, arg4);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function UpdateServiceTemplate(arg1) {
  return window['go']['main']['App']['UpdateServiceTemplate'](arg1);
}
