// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDocker() {
  return window['go']['main']['App']['CheckDocker']();
}

export function CreateNode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateNode'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteEnvVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1, arg2);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeployService(arg1) {
  return window['go']['main']['App']['DeployService'](arg1);
}

export function ExportEnvFile(arg1) {
  return window['go']['main']['App']['ExportEnvFile'](arg1);
}

export function GetActiveDeployment(arg1) {
  return window['go']['main']['App']['GetActiveDeployment'](arg1);
}

export function GetBuildLog(arg1) {
  return window['go']['main']['App']['GetBuildLog'](arg1);
}

export function GetDeployments(arg1) {
  return window['go']['main']['App']['GetDeployments'](arg1);
}

export function GetEnvVars(arg1) {
  return window['go']['main']['App']['GetEnvVars'](arg1);
}

export function GetLocalDomainStatus() {
  return window['go']['main']['App']['GetLocalDomainStatus']();
}

export function GetNodeSettings(arg1) {
  return window['go']['main']['App']['GetNodeSettings'](arg1);
}

export function GetProjectConnections(arg1) {
  return window['go']['main']['App']['GetProjectConnections'](arg1);
}

export function GetServiceMetrics(arg1) {
  return window['go']['main']['App']['GetServiceMetrics'](arg1);
}

export function GetServiceRoot(arg1, arg2) {
  return window['go']['main']['App']['GetServiceRoot'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportEnvFile(arg1, arg2) {
  return window['go']['main']['App']['ImportEnvFile'](arg1, arg2);
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function ListGitBranches(arg1) {
  return window['go']['main']['App']['ListGitBranches'](arg1);
}

export function ListNodes(arg1) {
  return window['go']['main']['App']['ListNodes'](arg1);
}

export function ListProjectServices(arg1) {
  return window['go']['main']['App']['ListProjectServices'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListReferenceTargets(arg1) {
  return window['go']['main']['App']['ListReferenceTargets'](arg1);
}

export function ParseDockerfileExpose(arg1, arg2) {
  return window['go']['main']['App']['ParseDockerfileExpose'](arg1, arg2);
}

export function PreviewEnvVars(arg1) {
  return window['go']['main']['App']['PreviewEnvVars'](arg1);
}

export function RefreshEnvFile(arg1) {
  return window['go']['main']['App']['RefreshEnvFile'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectServiceRoot(arg1) {
  return window['go']['main']['App']['SelectServiceRoot'](arg1);
}

export function SetEnvVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2, arg3);
}

export function SetEnvVarScope(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVarScope'](arg1, arg2, arg3);
}

export function SetNodeSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNodeSetting'](arg1, arg2, arg3);
}

export function SetServiceRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServiceRoot'](arg1, arg2, arg3);
}

export function StartLogStream(arg1) {
  return window['go']['main']['App']['StartLogStream'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function SuggestEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SuggestEnvFile'](arg1, arg2);
}

export function UpdateNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2, arg3, arg4);
}
