// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dockerwatch} from '../models';
import {store} from '../models';
import {main} from '../models';
import {networking} from '../models';
import {deploy} from '../models';
import {dockerfile} from '../models';

export function CheckDocker():Promise<dockerwatch.DaemonStatus>;

export function CreateNode(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<store.CanvasNode>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<store.Project>;

export function DeleteEnvVar(arg1:string,arg2:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeployService(arg1:string):Promise<void>;

export function ExportEnvFile(arg1:string):Promise<store.EnvFileSyncResult>;

export function GetActiveDeployment(arg1:string):Promise<store.Deployment>;

export function GetBuildLog(arg1:number):Promise<string>;

export function GetDeployments(arg1:string):Promise<Array<store.Deployment>>;

export function GetEnvVars(arg1:string):Promise<Array<store.EnvVar>>;

export function GetGitHookStatus(arg1:number):Promise<main.GitHookStatus>;

export function GetLocalDomainStatus():Promise<networking.LocalDomainStatus>;

export function GetNodeSettings(arg1:string):Promise<Record<string, string>>;

export function GetProjectConnections(arg1:number):Promise<Array<deploy.Connection>>;

export function GetServiceMetrics(arg1:string):Promise<deploy.ServiceMetrics>;

export function GetServiceRoot(arg1:string,arg2:number):Promise<string>;

export function ImportEnvFile(arg1:string,arg2:string):Promise<store.EnvFileSyncResult>;

export function IsGitRepo(arg1:number):Promise<boolean>;

export function ListGitBranches(arg1:number):Promise<Array<string>>;

export function ListNodes(arg1:number):Promise<Array<store.CanvasNode>>;

export function ListProjectServices(arg1:number):Promise<Array<main.ProjectService>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListReferenceTargets(arg1:string):Promise<Array<deploy.ReferenceTarget>>;

export function ParseDockerfileExpose(arg1:string,arg2:number):Promise<Array<dockerfile.ExposePort>>;

export function PreviewEnvVars(arg1:string):Promise<Record<string, deploy.EnvPreview>>;

export function RefreshEnvFile(arg1:string):Promise<store.EnvFileSyncResult>;

export function RestartService(arg1:string):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectServiceRoot(arg1:number):Promise<string>;

export function SetDeployTrigger(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetEnvVarScope(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetNodeSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetServiceRoot(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StartDocker():Promise<void>;

export function StartLogStream(arg1:string):Promise<void>;

export function StopLogStream(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SuggestEnvFile(arg1:string,arg2:number):Promise<string>;

export function UpdateNode(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;
