// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deploy} from '../models';
import {dockerwatch} from '../models';
import {store} from '../models';
import {main} from '../models';
import {draftpack} from '../models';
import {types} from '../models';
import {networking} from '../models';
import {agents} from '../models';
import {dockerfile} from '../models';

export function ApplySync(arg1:deploy.SyncRequest,arg2:string):Promise<deploy.SyncApplyResult>;

export function CheckDocker():Promise<dockerwatch.DaemonStatus>;

export function CloneServiceTemplate(arg1:number):Promise<store.ServiceTemplate>;

export function CloneVolumeData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<deploy.CloneVolumeResult>;

export function CreateEnvironment(arg1:number,arg2:string):Promise<store.Environment>;

export function CreateNode(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<store.CanvasNode>;

export function CreateNodeFromTemplate(arg1:deploy.CreateNodeFromTemplateRequest):Promise<deploy.CreateNodeFromTemplateResult>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<store.Project>;

export function CreateSandbox(arg1:deploy.SandboxCreateRequest):Promise<deploy.SandboxCreateResult>;

export function CreateServiceTemplate(arg1:store.ServiceTemplate):Promise<store.ServiceTemplate>;

export function DaemonConnection():Promise<main.DaemonConnectionInfo>;

export function DefaultDraftPackExportOptions():Promise<draftpack.ExportOptions>;

export function DeleteAppSecret(arg1:string):Promise<void>;

export function DeleteEnvVar(arg1:string,arg2:string):Promise<void>;

export function DeleteEnvironment(arg1:number):Promise<void>;

export function DeleteManagedVolume(arg1:string,arg2:boolean):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteProjectEnvVar(arg1:number,arg2:string):Promise<void>;

export function DeleteSandbox(arg1:number):Promise<void>;

export function DeleteSandboxProfile(arg1:number):Promise<void>;

export function DeleteServiceTemplate(arg1:number):Promise<void>;

export function DeployService(arg1:string):Promise<void>;

export function DiscardStagedChanges(arg1:string):Promise<void>;

export function DuplicateEnvironment(arg1:number,arg2:string,arg3:Array<deploy.ServiceDataChoice>,arg4:boolean,arg5:Array<deploy.SandboxRepositoryRef>):Promise<deploy.DuplicateEnvironmentResult>;

export function ExportConfig(arg1:string,arg2:string):Promise<deploy.ExportResult>;

export function ExportConfigToPath(arg1:string,arg2:string,arg3:string):Promise<deploy.ExportResult>;

export function ExportDraftPackEnvironment(arg1:number,arg2:draftpack.ExportOptions):Promise<draftpack.ExportResult>;

export function ExportDraftPackProject(arg1:number,arg2:draftpack.ExportOptions):Promise<draftpack.ExportResult>;

export function ExportDraftPackService(arg1:string,arg2:draftpack.ExportOptions):Promise<draftpack.ExportResult>;

export function ExportDraftPackToPath(arg1:string,arg2:string,arg3:number,arg4:number,arg5:draftpack.ExportOptions,arg6:string):Promise<draftpack.ExportResult>;

export function ExportEnvFile(arg1:string):Promise<store.EnvFileSyncResult>;

export function ExportProjectConfig(arg1:number,arg2:string):Promise<deploy.ExportResult>;

export function ExtendSandbox(arg1:number,arg2:number):Promise<store.Sandbox>;

export function ExtendSandboxUntil(arg1:number,arg2:string):Promise<store.Sandbox>;

export function GetActiveDeployment(arg1:string):Promise<store.Deployment>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetBuildLog(arg1:number):Promise<string>;

export function GetContainerLogHistory(arg1:string,arg2:number):Promise<deploy.LogHistory>;

export function GetDefaultEnvironment(arg1:number):Promise<store.Environment>;

export function GetDeployments(arg1:string):Promise<Array<store.Deployment>>;

export function GetDockerDiskUsage():Promise<types.DiskUsage>;

export function GetEnvVars(arg1:string):Promise<Array<store.EnvVar>>;

export function GetEnvironmentConnections(arg1:number):Promise<Array<deploy.Connection>>;

export function GetGitHookStatus(arg1:string,arg2:number):Promise<main.GitHookStatus>;

export function GetLinkedServiceInfo(arg1:string):Promise<deploy.LinkedServiceInfo>;

export function GetLocalDomainStatus():Promise<networking.LocalDomainStatus>;

export function GetNode(arg1:string):Promise<store.CanvasNode>;

export function GetNodeConfigStatus(arg1:string):Promise<deploy.NodeConfigStatus>;

export function GetNodeHealth(arg1:string):Promise<deploy.NodeHealth>;

export function GetNodeSettings(arg1:string):Promise<Record<string, string>>;

export function GetSandboxDetail(arg1:number):Promise<deploy.SandboxDetail>;

export function GetSandboxProjectSettings(arg1:number):Promise<store.SandboxProjectSettings>;

export function GetSandboxTestRun(arg1:number):Promise<deploy.SandboxTestRunResult>;

export function GetServiceMetrics(arg1:string):Promise<deploy.ServiceMetrics>;

export function GetServiceRoot(arg1:string,arg2:number):Promise<string>;

export function GetServiceTemplate(arg1:number):Promise<store.ServiceTemplate>;

export function ImportConfigAsProject(arg1:string,arg2:string):Promise<deploy.ImportResult>;

export function ImportConfigIntoProject(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number):Promise<deploy.ImportResult>;

export function ImportConfigPreview(arg1:string):Promise<deploy.ImportPreview>;

export function ImportDraftPack(arg1:string,arg2:draftpack.ImportOptions):Promise<draftpack.ImportResult>;

export function ImportDraftPackJSON(arg1:string,arg2:draftpack.ImportOptions):Promise<draftpack.ImportResult>;

export function ImportEnvFile(arg1:string,arg2:string):Promise<store.EnvFileSyncResult>;

export function InspectDockerfileBuildInfo(arg1:string):Promise<deploy.DockerfileBuildInfo>;

export function IsGitRepo(arg1:string,arg2:number):Promise<boolean>;

export function LinkToSharedRoot(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAgentSessions():Promise<Array<agents.SessionInfo>>;

export function ListAgents():Promise<Array<agents.AgentInfo>>;

export function ListAllDockerVolumes():Promise<Array<deploy.VolumeOverview>>;

export function ListAppSecretUsages(arg1:string):Promise<Array<deploy.SecretUsage>>;

export function ListAppSecrets():Promise<Array<store.AppSecret>>;

export function ListDockerContainers():Promise<Array<deploy.ContainerSummary>>;

export function ListDockerImages():Promise<Array<deploy.ImageSummary>>;

export function ListDockerNetworks():Promise<Array<deploy.NetworkSummary>>;

export function ListEnvironments(arg1:number):Promise<Array<store.Environment>>;

export function ListGitBranches(arg1:string,arg2:number):Promise<Array<string>>;

export function ListManagedVolumes(arg1:number,arg2:string):Promise<Array<deploy.ManagedVolume>>;

export function ListNodes(arg1:number):Promise<Array<store.CanvasNode>>;

export function ListNodesWithReferenceIssues(arg1:number):Promise<Array<string>>;

export function ListProjectEnvVarUsages(arg1:number,arg2:string):Promise<Array<deploy.SecretUsage>>;

export function ListProjectEnvVars(arg1:number):Promise<Array<store.ProjectEnvVar>>;

export function ListProjectServices(arg1:number):Promise<Array<main.ProjectService>>;

export function ListProjectServicesSummary(arg1:number):Promise<main.ProjectServicesSummary>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListReferenceIssues(arg1:string):Promise<Array<deploy.ReferenceIssue>>;

export function ListReferenceTargets(arg1:string):Promise<Array<deploy.ReferenceTarget>>;

export function ListRoutes(arg1:any):Promise<Array<main.RouteRow>>;

export function ListSandboxProfiles(arg1:number):Promise<Array<store.SandboxProfile>>;

export function ListSandboxSourceRepos(arg1:number):Promise<deploy.SandboxSourceRepos>;

export function ListSandboxTestRuns(arg1:number,arg2:number):Promise<Array<store.SandboxTestRun>>;

export function ListSandboxes(arg1:number):Promise<Array<store.Sandbox>>;

export function ListServiceTemplates():Promise<Array<store.ServiceTemplate>>;

export function ListShareTargets(arg1:string):Promise<Array<deploy.ShareTargetEnvironment>>;

export function ListShareableRoots(arg1:number,arg2:number):Promise<Array<deploy.RootServiceSummary>>;

export function ListVolumesOverview():Promise<Array<deploy.VolumeOverview>>;

export function MintShellAttach(arg1:string,arg2:string):Promise<main.ShellAttachInfo>;

export function ParseDockerfileExpose(arg1:string,arg2:number,arg3:string):Promise<Array<dockerfile.ExposePort>>;

export function PreviewCloneVolume(arg1:string,arg2:string,arg3:string):Promise<deploy.CloneVolumePreview>;

export function PreviewDeleteService(arg1:string):Promise<deploy.DeleteServicePreview>;

export function PreviewDraftPackImport(arg1:string,arg2:draftpack.PreviewOptions):Promise<draftpack.ImportPreview>;

export function PreviewDraftPackJSON(arg1:string,arg2:draftpack.PreviewOptions):Promise<draftpack.ImportPreview>;

export function PreviewEnvVars(arg1:string):Promise<Record<string, deploy.EnvPreview>>;

export function PreviewEnvironmentDuplicate(arg1:number):Promise<Array<deploy.StatefulServiceSummary>>;

export function PreviewLinkToSharedRoot(arg1:string,arg2:string):Promise<deploy.LinkToSharedRootPreview>;

export function PreviewSandbox(arg1:deploy.SandboxCreateRequest):Promise<deploy.SandboxPreview>;

export function PreviewSandboxPurge(arg1:number):Promise<deploy.SandboxPurgeInventory>;

export function PreviewStagedChanges(arg1:string,arg2:Record<string, string>):Promise<deploy.StagedChangePreview>;

export function PreviewSync(arg1:deploy.SyncRequest):Promise<deploy.SyncPreview>;

export function PromoteLinkedService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PruneDocker(arg1:string,arg2:boolean):Promise<deploy.PruneReport>;

export function ReapplyTemplate(arg1:string):Promise<deploy.CreateNodeFromTemplateResult>;

export function RedeployEnvironment(arg1:number):Promise<deploy.EnvironmentStackResult>;

export function RefreshEnvFile(arg1:string):Promise<store.EnvFileSyncResult>;

export function RefreshLocalDomainStatus():Promise<networking.LocalDomainStatus>;

export function RefreshSandbox(arg1:number,arg2:string):Promise<deploy.SandboxRefreshResult>;

export function RemoveDockerContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveDockerImage(arg1:string,arg2:boolean):Promise<void>;

export function RemoveDockerNetwork(arg1:string):Promise<void>;

export function RemoveDockerVolume(arg1:string,arg2:boolean):Promise<void>;

export function RenameEnvironment(arg1:number,arg2:string):Promise<void>;

export function ResizeAgentSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveSandboxRef(arg1:string,arg2:string,arg3:string):Promise<store.SandboxRepositorySource>;

export function RestartDockerContainer(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function ResumeSandbox(arg1:number):Promise<store.Sandbox>;

export function RollbackDeployment(arg1:number):Promise<void>;

export function RollbackEligibility(arg1:string):Promise<Array<deploy.RollbackEligibility>>;

export function RunCommand(arg1:string,arg2:Array<string>,arg3:string):Promise<deploy.RunCommandResult>;

export function RunTestingSandbox(arg1:deploy.SandboxTestRunRequest):Promise<deploy.SandboxTestRunResult>;

export function SaveDraftPackFile(arg1:string):Promise<string>;

export function SaveSandboxProfile(arg1:store.SandboxProfile):Promise<store.SandboxProfile>;

export function SaveSandboxProjectSettings(arg1:store.SandboxProjectSettings):Promise<store.SandboxProjectSettings>;

export function SelectDraftPackFile():Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectServiceRoot(arg1:number):Promise<string>;

export function SetAppSecret(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAppSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function SetDefaultEnvironment(arg1:number):Promise<void>;

export function SetDeployTrigger(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetEnvVarScope(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetGitDeploymentConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetLocalDraftDomainEnabled(arg1:boolean):Promise<networking.LocalDomainStatus>;

export function SetNodeSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProjectEnvVar(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetRedeployOnPull(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetServiceRoot(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StageEnvVarChanges(arg1:string,arg2:Array<store.EnvVarStageUpsert>,arg3:Array<string>):Promise<void>;

export function StageNodeSettings(arg1:string,arg2:number,arg3:Record<string, string>):Promise<void>;

export function StartAgentSession(arg1:agents.StartSessionRequest):Promise<agents.SessionInfo>;

export function StartDocker():Promise<void>;

export function StartDockerContainer(arg1:string):Promise<void>;

export function StartEnvironment(arg1:number):Promise<deploy.EnvironmentStackResult>;

export function StartLogStream(arg1:string):Promise<void>;

export function StopAgentSession(arg1:string):Promise<void>;

export function StopDockerContainer(arg1:string):Promise<void>;

export function StopEnvironment(arg1:number):Promise<deploy.EnvironmentStackResult>;

export function StopLogStream(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SuggestEnvFile(arg1:string,arg2:number):Promise<string>;

export function SuspendSandbox(arg1:number):Promise<store.Sandbox>;

export function UnlinkService(arg1:string,arg2:string):Promise<void>;

export function UpdateNode(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateServiceTemplate(arg1:store.ServiceTemplate):Promise<void>;

export function WriteAgentSession(arg1:string,arg2:string):Promise<void>;
